services:
  - type: web
    name: ai-email-drafter
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.enableCORS false
    plan: free
